apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: test-liveness-http
spec:
  containers:
  - name: liveness
    image: nginx:1.8
    livenessProbe:
      httpGet:
        path: /
        port: 80
        httpHeaders:
        - name: X-Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
